apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    tier: backend
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: api
  selector:
    app: api
    tier: backend
