apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cronworker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cronworker
        tier: backend
    spec:
      containers:
        - name: cronworker
          image: node
          command: ["sh", "-c", "while true; do curl -X POST -i https://jffr.se/cron; sleep 10; done;"]
