apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronworker
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronworker
            image: byrnedo/alpine-curl:0.1.5
            args:
            - -X
            - POST
            - https://jffr.se/cron
          restartPolicy: OnFailure
