apiVersion: v1
kind: Service
metadata:
  name: drone-server
  labels:
    app: drone-server
    tier: backend
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: drone-broker
  selector:
    app: drone-server
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-agent
        tier: backend
    spec:
      containers:
        - name: drone-agent
          image: drone/agent:0.8
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: DRONE_DEBUG
              value: "true"
            - name: DRONE_SERVER
              value: drone-server:9000
            - name: DRONE_SECRET
              value: ZrLdDiOJlQyWkYOWIlJ4kxoTlEbaszllBFZ1mavAuY0ZJiV423PILTWUvAbz
            - name: DRONE_MAX_PROCS
              value: "3"
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: google-cloud-key
              mountPath: /var/secrets/google
      volumes:
        - name: google-cloud-key
          secret:
            secretName: jeffrey-api-key
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-server
        tier: backend
    spec:
      containers:
        - name: drone-server
          image: drone/drone:0.8
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 9000
              name: drone-broker
          env:
            - name: DRONE_DEBUG
              value: "true"
            - name: DRONE_HOST
              value: https://drone.jffr.se
            - name: DRONE_OPEN
              value: "true"
            - name: DRONE_SECRET
              value: ZrLdDiOJlQyWkYOWIlJ4kxoTlEbaszllBFZ1mavAuY0ZJiV423PILTWUvAbz
            - name: DRONE_ADMIN
              value: appleboy
            - name: DRONE_GITHUB
              value: "true"
            - name: DRONE_GITHUB_CLIENT
              value: 85bb639e93ae4f9528aa
            - name: DRONE_GITHUB_SECRET
              value: f7ac0f24eac2a0b74263accbc7364cdd20cb9597
            - name: DRONE_ORGS
              value: jeffreytech
            - name: DRONE_DATABASE_DRIVER
              value: postgres
            - name: DRONE_DATABASE_DATASOURCE
              value: postgres://proxyuser:MswMfPSs@127.0.0.1:5432/drone?sslmode=disable
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=jeffrey-197808:europe-west1:api-production=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
