apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-agent
        tier: backend
    spec:
      containers:
        - name: drone-agent
          image: drone/agent:0.8
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: DRONE_DEBUG
              value: "true"
            - name: DRONE_SERVER
              value: drone-server:9000
            - name: DRONE_SECRET
              value: ZrLdDiOJlQyWkYOWIlJ4kxoTlEbaszllBFZ1mavAuY0ZJiV423PILTWUvAbz
            - name: DRONE_MAX_PROCS
              value: "3"
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: google-cloud-key
              mountPath: /var/secrets/google
      volumes:
        - name: google-cloud-key
          secret:
            secretName: jeffrey-api-key
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
