apiVersion: v1
kind: Service
metadata:
  name: drone-server
  labels:
    app: drone-server
    tier: backend
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: drone-broker
  selector:
    app: drone-server
    tier: backend

