apiVersion: v1
kind: Service
metadata:
  name: el-chacouch-landing-page
  labels:
    app: el-chacouch-landing-page
    tier: backend
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: el-chacouch-landing-page
    tier: backend
