apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gateway
        tier: backend
    spec:
      containers:
        - name: gateway
          image: eu.gcr.io/jeffrey-197808/gateway:1.11
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          env:
            - name: LETSENCRYPT_CONTACT_EMAIL
              value: "william@reptilians.io"
