apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    name: gateway
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http-server
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https-server
  selector:
    name: gateway
