apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    tier: backend
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: gateway
    tier: backend
