apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocket-chat-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocket-chat-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        tier: backend
    spec:
      containers:
        - name: master
          image: mongo:3.2
          command: ["mongod",
                    "--smallfiles",
                    "--oplogSize",
                    "128",
                    "--replSet",
                    "rs0",
                    "--storageEngine=mmapv1"]
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: rocket-chat-persistent-storage
              mountPath: /data/db
      volumes:
        - name: rocket-chat-persistent-storage
          persistentVolumeClaim:
            claimName: rocket-chat-disk
---
apiVersion: v1
kind: Service
metadata:
  name: rocket-chat-db
  labels:
    app: mongo
    tier: backend
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb-server
  selector:
    app: mongo
    tier: backend
