apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shell
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
        - name: shell
          image: nginx:latest
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: google-cloud-key
          secret:
            secretName: jeffrey-api-key
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
