environment: production
protocol: https
host: staging.jeffrey-services.com
webappProtocol: https
webappHost: app.prestine.io
mailgun:
  apiBaseURL: https://api.mailgun.net/v3/prestine.io
  apiKey: key-4uxc32rva7pgw0ia1blpcmgjjznh3y82
logentries:
  token: 3a6ab0cb-5727-43f3-994a-efc38cdf1be7
northsigner:
  appId: 6d3bb2f0576825cc7a96095404b1378c
  appSecret: aee460338f422db44cf50d0aaa28b273
recaptcha:
  secretKey: 6Ld0SBgUAAAAAFwoHvMbWZ6nx7iKszRC6ioWAArF
db:
  client: 'pg'
  connection:
    user: postgres
    database: postgres
    host: postgres
    password: ''
    port: 5432
    max: 10
    idleTimeoutMillis: 30000
  debug: false
stripe:
  secretKey: sk_test_QiJITpQTx1S0NkFv3DiySXi3
twilio:
  accountSid: AC410a7b5e527762412690b23e1be2d6bb
  authToken: 6801847ac16da1a775cf78d6f9713c20
  twiMlAppSid: APad1bdd10f77fc6eda6fa083d3134dc40
  apiKey: SK496bc4825277985ca583427ec80f8b79
  apiSecret: XB12YR7nWAHeQFaRhGikcxzp1QvwcoN0
  pushCredentialSid: CRdf35b76c52e777b665bab285c03e31ef
app:
  phoneNumberProductId: c20ff7a5-bd85-479a-96ff-a429b5be8b59
  incomingMessageProductId: cfe1028a-b175-4f32-8087-a67e0b5efddf
  outgoingMessageProductId: 8739cdec-413c-459f-94f3-248fb43c49db
  tenEurosCreditProductId: cfcc7d2d-b704-4083-a775-38b9d229cc90
vapidDetails:
  subject: https://prestine.io
  publicKey: BFARvvLAfWlPm9fGIYMWdOsPXxIfpkRMyi-Cdd1Z6iFAHz8Za84IEVjWGc79yTkSFPkIOQiK9_xyxsfzDunupyU
  privateKey: IDjxpa0emSfXZ9QNlCFeA02nphS99ogrTtpBXeGRQ24
redis:
  host: redis
  port: 6379
jwt:
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAywpyHT9Guf8ev1uEzCvr
    KpA7gzBshcp1f5ZyTvqm63AcvaiqlXl5N4K7QYXIIEFqypmBPkkPXlpDME4OF9sE
    T+J+XHKWKrtZNC90Cl3xdBF3149faGRTqyjZzhLSIcsNrmD8V+KJD9ooZ03LONNd
    apoorXkeNXltXzXDla4G9vWE6fUuUtDqWXR5a0G0ZfBdZ6EG+oZPmuq57F07c2de
    1izueGueKI9fzFnX0gG8NVOsaEJhN4U59mWy7m16GDecyiGlln1KbxC/AS+VR6L4
    uyxeeXrulzkhmvpsis+tcEz1FduxaT7eNRqFCyvfX8NSvKMyltOdrQ3q44ZJixIV
    o+ADu7HylSvHWgGF8W1ulwzykWEBB5qbAPgl7tzr0DIJ4BYRcJIPGRsd8w2zsuuj
    UF7M4tr89gAvShsaBHniqIW07oxSqmwQgtJHJ8rGu8ogBKE0U6B0qRSb+3xIoQPl
    Lmzw5RiM2Wg3GDtzybeLwtHgbvZGptF+SEnGPvfnTJ/92dgkYRJyB/RyZF0LrPWX
    yn930d9zNyyoif5SFIgTuKj0qRGsMrrHQ7vyjU4RGkOGYCyun1rNGmoJj7Owt3SB
    fwqGcOsEHyZOJ079sMrIbCWAohvi6KwcQhLDBKFDEalJDNOixeqjoGnK9GBAqwnj
    dut+wTGlh2rtWHfbkWSQmBkCAwEAAQ==
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKQIBAAKCAgEAywpyHT9Guf8ev1uEzCvrKpA7gzBshcp1f5ZyTvqm63Acvaiq
    lXl5N4K7QYXIIEFqypmBPkkPXlpDME4OF9sET+J+XHKWKrtZNC90Cl3xdBF3149f
    aGRTqyjZzhLSIcsNrmD8V+KJD9ooZ03LONNdapoorXkeNXltXzXDla4G9vWE6fUu
    UtDqWXR5a0G0ZfBdZ6EG+oZPmuq57F07c2de1izueGueKI9fzFnX0gG8NVOsaEJh
    N4U59mWy7m16GDecyiGlln1KbxC/AS+VR6L4uyxeeXrulzkhmvpsis+tcEz1Fdux
    aT7eNRqFCyvfX8NSvKMyltOdrQ3q44ZJixIVo+ADu7HylSvHWgGF8W1ulwzykWEB
    B5qbAPgl7tzr0DIJ4BYRcJIPGRsd8w2zsuujUF7M4tr89gAvShsaBHniqIW07oxS
    qmwQgtJHJ8rGu8ogBKE0U6B0qRSb+3xIoQPlLmzw5RiM2Wg3GDtzybeLwtHgbvZG
    ptF+SEnGPvfnTJ/92dgkYRJyB/RyZF0LrPWXyn930d9zNyyoif5SFIgTuKj0qRGs
    MrrHQ7vyjU4RGkOGYCyun1rNGmoJj7Owt3SBfwqGcOsEHyZOJ079sMrIbCWAohvi
    6KwcQhLDBKFDEalJDNOixeqjoGnK9GBAqwnjdut+wTGlh2rtWHfbkWSQmBkCAwEA
    AQKCAgBBmKVXZ5r8+jw/zFxx7fpy7NgdQSa+brNZPgy+EWKeC8FtULGTywPreDPx
    LjyClz/eJovHyKjLbdPpJj6NXHffKyhxy59SPObL4kzWEJWyTvZt0Occ/dS+Jlt/
    pTr4KfbIkJLV/d0UHwIQpeRy/m5ew2FC8i9dTVaVfPQsRmX/oUCIqWqG3PHpZqTX
    jwmuKWKz2SU9COls/kqE33YWiZ3tCeUdSH93USK9DYWZVnAstlSr9k4cNtGMFj0h
    pILekhD4iLhLjzzd9wYOZwYOd8tuBR6clqfAeXeu7xrkGcZJ0sMXhbuiaeo2M9Qp
    0MnA0YTIZt0wNzvoredmDHt0D6qni+WNiEKcqIyVuloKf6qMg0scZU0vkMGyiI9Z
    h8XpLaWUbkOK7fIceh0DgiPDDan/UdW7tNuXAoyCZd/gKl9ljyeOf9zbb3jMM0B7
    auKHcw9ncQ+XlsGi5NHOH/UugLJzBKvTMY0u2C8M8nej6ItbvFo6cz0TZZXDFDEE
    M9TlipTskGj/UP+jbwCpWBMfPeBZx1/LpNwrEbh79bxqdjtNRnS41H4FmyKcAEvV
    orMZzRfQ54bPzTPV7C2iII+oTemuyOWBCjc+gLtiakZFruW9MelcZofmwcjcQEPB
    7NAKGFad3SfYQDR0XrU2OQLYYLp1fuysqJoUbu9YBn24f+YSdQKCAQEA/EFs1p26
    Ei/oMBQqwcTeL4EyDEgwIOEy8FBaT8HGQXRThkNyk0dUXor2lZb74J0J4UZnwRAX
    rBp1CVWvguT/A8aw7AkWId/o+WF0FBmbCGknpnWRnhkofbp9qEXrgHGeWHwKIpxB
    D5yxJfpP8WuGGgPwgDf5/QmD62WKrnPY8yzJbaWGBgFe1/GhwzfrO0EU33iTcn6m
    +2FvEJD52cR2tUUEZjzTKJiHYaF/mbMIpRqOe6rmsDI4Hc0PlfXvJrZShs9eWUkN
    g7OWwcy6+JLHKDaXQWp9weTJOLnYhRJsYxmI1BbdQPL4EQqyZJ/2lf71v+d0nuVS
    knMsa6bhc3wN6wKCAQEAzg4A+DoWcKSVgttIZaToZWjEd1GvGtJF8drBC1nubSKZ
    qHVQvT9RYxJU8sVR4ryz3crMwYBLRxC42Dw5d5g7jv/cfr43XhOWO0KmBbPuWtW5
    odpH6VCEFAAz98ikotcDf3ZqqxGP5vlyii46ylSQJhHtCeLTcK4qnyjT26cQMpvN
    VPFcCLd1ofwq4DC+aj3a1Pjoc5uJ/cB6KnVBfBlcy+tVGNjdb2HnFUSEINBMHLPt
    2NI0jJ/BTTiXZpqZIWiBArbRw/0yf5ogqq9GKbTBM55u0nA6h/JcOBEBQNBOgWkB
    WNdTp4RsGI2052k3Fm6gwlNp9nq+c54t3QGRMwE9CwKCAQEAr0FVOJZEnDYkfqLE
    QfNg2mhMOTQ+G9nZ5hQtapQaBYeoL/PUOnaoKzcosi0/uYHhR13+36cqiyumfGHH
    mo02j40Phi2Z7tb9qaUHXJ+dkm5cWc386XZZJ2DVxH8vawGFHbyv3fPpT8txWA1c
    VUJ63MA36xz41dAykuztON7Lr8dB+qexQaLaHfWGiXbkOzqwIcJHzpgnsyayXzQa
    Ii3Yu3/D2rQPkHjINhBZ8pLsQqj8rPbDZ068phe96FYBXUf2dirERgv3E7VF3Ec8
    704qh8nFtHEkBf3Jv1t/DpUKMJ+g7JkmBuXHay+fWUG5s+R7IGTSJUL150GVbwV2
    RSG/GQKCAQBlkr2jn27EZD1XXiUYBeyRYM3IS7nXrOPRzxXuNIy1u6KnSf1c7MN/
    5N9/NQmijYbUxE2e7VEuXO3hmf5yF9b0LOhSig3dECa0W6xfj0zl9gkl4eYk+w3A
    lkEH2h5eL0OIJ6V5YpTfNQPjXdqZNopAWgHRJ8E3AIP+JTAaTQZNDERxpPDLUzRn
    f1jbXuvej1M6PODJbFjff2w5VcfMFuyJkR5Hu0+cwlQZRcckLcn3NDMA+M3yrCWr
    nUP0zizCLTO7VMeep0enYyDLQs+Ba5r5iRX0ImKX9T7EXI2Tl5u7aznAw5R3NW3b
    xK7yjAkdw7b3VAsd92++qrDNCyK6U9f1AoIBAQDumXgv98ia6llcGvIReZ0KPRnx
    xg8wZBk285ZUiyqmNWZGxdDZellBJkaGQK++nKn1WDdA84r5mdsFGnUSi0E1RivM
    f2ph480SLX+1Dt5j3565bXMTUxwO/qc8BLiGwHpT6Rg9R0N87BrgNsLisR7pIPZD
    B151PZsOlZMvtceQeMqb091QFAXCwTF1XYGyr2tviJ7zcHSXD+enygErz3JZa934
    SP0iMS8e63fsGCLiNAAyV7bHcTVaTr3Lt8uAU8nuRN7/Lfqu4Q/Ft+4ehDLuNimK
    uu1fOii0wbhvcekVf0PPidsOXNNTmoN66tJQc81u9xIE1XdpI/doR1yHb67J
    -----END RSA PRIVATE KEY-----
