version: '2'
services:
  jeffrey_api_v2:
    restart: always
    image: jffr/api:latest
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config.yml:/config.yml
    environment:
      CONFIG: /config.yml
      NODE_ENV: production
    ports:
      - "127.0.0.1:3000:80"
  redis:
    restart: always
    image: redis:3.0
  postgres:
    restart: always
    image: postgres:10.1
    volumes:
      - ./pg_data:/var/lib/postgresql/data
